apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rjb76545p-dotnet-basic-gitops
  description: This is GitOps manifest for rjb76545p-dotnet-basic   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: rjb76545p-dotnet-basic
    backstage.io/kubernetes-id: rjb76545p-dotnet-basic 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: rjb76545p-dotnet-basic   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:rjb76545p-dotnet-basic
