apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: rjb76545p-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/rjb76545p-dotnet-basic-gitops